package ru.ifmo.se.johnwick.model;

public enum OrderStatus {
    CREATED,
    AWAITING_APPLICATIONS,
    AWAITING_ASSIGNEE,
    AWAITING_SUIT,
    AWAITING_DEGUSTATION,
    AWAITING_SUBMISSION,
    AWAITING_CLEANING,
    AWAITING_APPROVAL,
    COMPLETED,
    CANCELLED
}
