baba-yaga:
  regular-order:
    cancellation-interval: PT1M
    max-age-for-cancellation: PT5M # 5 minutes
  head-hunt-order:
    price-increase-interval: PT1M
    price-increase-factor: 0.05

quarkus:
  http:
    auth:
      basic: true
  datasource:
    db-kind: postgresql
    username: postgres
    password:
    jdbc:
      url: jdbc:postgresql://localhost:5432/johnwick
  flyway:
    migrate-at-start: true

"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      username: postgres
      password: postgres
      jdbc:
        url: jdbc:postgresql://localhost:5432/johnwick
    flyway:
      migrate-at-start: true
    hibernate-orm:
      log:
        bind-parameters: true
        sql: true
    log:
      level: INFO
